### ISSUE TITLE
Player: Playbar dissapears at random

### ISSUE THREAD

**Issue by agusave82** [polimediaupv/paella#191] opened 2016-02-10 14:21 UTC
This is a non-deterministic bug.
The bar usually dissapears when leaving the cursor out of the player for some time, but that is correct behaviour.
The problem is that sometimes it is not shown again (or ever) when coming back to the player with the cursor, as it should.

We need to find how to reproduce this bug reliably.

**Comment by turro** [comment] 2016-02-10 14:24
Hi agusave82

We are aware of this bug and we are going to fix it in the new Paella Player release. The bug arises because of race conditions between the plugins.

Expect to have it fixed on the release 5 that we are going to launch in March

**Comment by turro** [comment] 2016-02-10 14:28
@agusave82: May I know where are you from?

**Comment by spiraleddy** [comment] 2016-02-10 14:32
We also have seen this at HU-DCE. It seems to be very common, but  no one cannot reliably reproduce (it happens when you are not trying to make it happen). We are very eager for the fix!

**Comment by agusave82** [comment] 2016-02-10 14:34
Hi turro

I'm from Vigo, I belong to the company Teltek Video Research

**Comment by turro** [comment] 2016-02-10 14:37
We can't reproduce also. We have solved that in PP5 by adding the promises library (https://www.promisejs.org/), and that doesn't happen AFAIK

**Comment by rubenrua** [comment] 2016-02-10 15:46
@turro :+1: we love promises.

**Comment by miesgre** [comment] 2016-03-08 20:20
Fixed in Paella 5.0.0

**Closed by miesgre** 2016-03-08 20:20 UTC
