### ISSUE TITLE
I can't forward or backward in HLS video with Paella 6.4.1 version

### ISSUE THREAD

**Issue by markham89** [polimediaupv/paella#530] opened 2020-04-09 05:28 UTC
# Describe the bug
I can't forward or backward in HLS video when video are not totatlly precharged  with Paella 6.4.1 version
(i have a black screen on video)

# To Reproduce

Play video and click on the timeline
(simple video, or image + video, same issue)

# Environment Information
Macosx Mojave
Google chrome 81
Firefox 75
Microsoft edge (chromium version)

# Additional context
i Use paella on a regular Apache 2 server,
no issue with previous version (6.1.3 or 5)

Thanks

**Comment by turro** [comment] 2020-04-09 09:56
Hi Markham

We've been unable to reproduce. Please test again with https://paellaplayer.upv.es/demos/multi-quality-hls/ , that is a demo with 6.4.1 with our HLS server.

There should be something in your HLS server

**Comment by markham89** [comment] 2020-04-09 10:24
Your video does'nt work for me :
[https://ibb.co/PwQtshV](https://ibb.co/PwQtshV)
see (xhr call canceled, pending, same issue for me)

**Comment by markham89** [comment] 2020-04-10 05:52
same issue with firefox
it's new browser behaviours [https://stackoverflow.com/questions/12009423/what-does-status-canceled-for-a-resource-mean-in-chrome-developer-tools?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](https://stackoverflow.com/questions/12009423/what-does-status-canceled-for-a-resource-mean-in-chrome-developer-tools?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)


screenshot :

[https://ibb.co/7JVmDbn](https://ibb.co/7JVmDbn)

**Comment by markham89** [comment] 2020-04-12 13:21
any idea ?

**Comment by turro** [comment] 2020-04-12 13:29
Hi Markham

I updated to Chrome  81.0.4044.92 (64 bits) and I am unable to reproduce. 

Could that be something with your proxy server?. I don't know what to look more.

Anyway, we are in the middle of the Easter week. Next week we may test more and try to reproduce the issue

**Comment by markham89** [comment] 2020-04-12 14:21
try with slow speed connection (i have adsl)  and empty internet cache.
no problem with a fiber connection because the video is completely preloaded.

try with last version firefox.

i have no proxy, just  adsl connection and empty cache.

**Comment by markham89** [comment] 2020-04-12 15:35
Ok there are 2 issues :

1) Slow network speed paella Behavior (HLS video resume failed. Trying to recover. on firefox)
xhr canceled on chrome


2) autoplay-option (disable by defaut on firefox)

**Comment by turro** [comment] 2020-04-13 11:16
Now I see it. I've used the developer tools to simulate a low bandwidth connection and that happens. 

Could you try to add a sensible value for fragloadingtimeout and levelloadingtimeout in the config .json?. My guess is that is not directly related to Paella, but with hls.js library

Look at https://github.com/video-dev/hls.js/blob/master/docs/API.md#fragloadingtimeout--manifestloadingtimeout--levelloadingtimeout

Regarding the autoplay it's something up to the browser to honor it or not. I think ttat at some point in the future all browsers will kill it

**Comment by markham89** [comment] 2020-04-13 14:24
I try to create and modify parameter fragloadingtimeout  and  and levelloadingtimeout without succes :

i have the same message in console :
HLS video resume failed. Trying to recover.


while the hls.js test site  work perfectly 
[https://hls-js.netlify.com/demo/](https://hls-js.netlify.com/demo/)

**Comment by markham89** [comment] 2020-04-22 17:35
Any ideas ?

**Comment by turro** [comment] 2020-04-23 08:09
We've been testing and we don't know exactly what is happenning. 

First of all seems that the demo is doing something strange Because when you change the URL works some times and sometimes not. 

I configured in Chrome a ADSL connection (2Mb upload 1MB dowload 90 msec latency) and basically stucks forever both for our demo video and the hls.js video. Note that cache is disabled.

The way to reproduce is to change the streaming URL, click on apply and then with the developer tools open click reload. There is no cancelled, but I've checked in our case and the cancelled got retried, so that was not the issue.

Have a look to this tests

hls.js demo
![image](https://user-images.githubusercontent.com/3541284/80074091-f606c600-8548-11ea-9f8c-0642510f893a.png)

then I changed to paella demo and seems it's working... sometimes
https://streaming.upv.es/paellaplayerdemo/_definst_/smil:belmar-hls/belmar/playlist.m3u8

No more ideas at this point. Could you try an iOS device with your settings?. Just to test if it is the same behaviour with the iOS hls native client



Our current thoughts point to a hls.js config. However we haven't been able to identify it, since 

We've been looking into this
https://github.com/video-dev/hls.js/blob/master/docs/API.md#fine-tuning

Could you try in your installation to lower these?

maxBufferLength (default: 30 seconds)
Maximum buffer length in seconds. If buffer length is/become less than this value, a new fragment will be loaded. This is the guaranteed buffer length hls.js will try to reach, regardless of maxBufferSize.

maxBufferSize (default: 60 MB)
'Minimum' maximum buffer size in bytes. If buffer size upfront is bigger than this value, no fragment will be loaded.

There are also some more values, but seems like a trial& error thing

**Comment by markham89** [comment] 2020-04-23 19:39
I try several scenarios with old versions who's works
i try several hls.mis.js version
i try old hls config to replace actual hls config
i try custom hls config
conclusion :
new paella_player.js and new paella_player_es2015.js introduce bugs !

this old paella file (attach file) works without any bug with low connection, no latency, no erro message

[paella.zip](https://github.com/polimediaupv/paella/files/4524816/paella.zip)

**Comment by markham89** [comment] 2020-04-24 06:09
Hi,
I just fix the problem when i remove (comment) this part  :

line : 14177

`console.debug("HLS video resume failed. Trying to recover.");
							if (this._hls) {
								this._hls.recoverMediaError();
						                  }
							else {
								//iOS
						In this way the recharge is forced, and it is possible to recover errors.
								let src = this.video.innerHTML;
								this.video.innerHTML = "";
								this.video.innerHTML = src;
								this.video.load();
								this.video.play();
							}`

no error, it's works !

**Closed as completed** 2020-04-24 06:41 UTC
Labels: bug

**Comment by turro** [comment] 2020-04-24 06:45
Thanks a lot @markham89 !!!
